apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker1
  labels:
    app: broker
    instance: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
      instance: "1"
  strategy: {}
  template:
    metadata:
      labels:
        app: broker
        instance: "1"
    spec:
      containers:
      - image: ciberkleid/s1p-2020-mesh-rs-broker:0.0.1-SNAPSHOT
        name: broker
        envFrom:
          - configMapRef:
              name: broker-list
        env:
#          - name: SPRING_PROFILES_ACTIVE
#            value: "k8s-scaled"
          - name: CLUSTER_NODE_1
            value: broker2
          - name: CLUSTER_NODE_2
            value: broker3
        resources: {}
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: broker1
  labels:
    app: broker
    instance: "1"
spec:
  ports:
    - name: proxy-port
      port: 8002
      protocol: TCP
      targetPort: 8002
    - name: cluster-port
      port: 7002
      protocol: TCP
      targetPort: 7002
  selector:
    app: broker
    instance: "1"
  type: ClusterIP
status:
  loadBalancer: {}
