apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker2
  labels:
    app: broker
    instance: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
      instance: "2"
  strategy: {}
  template:
    metadata:
      labels:
        app: broker
        instance: "2"
    spec:
      containers:
        - image: marygabry1508/s1p-2020-mesh-rs-broker:0.0.1-SNAPSHOT
          name: broker
          envFrom:
            - configMapRef:
                name: broker-list
          env:
            - name: CLUSTER_NODE_1
              value: broker1
            - name: CLUSTER_NODE_2
              value: broker3
          resources: {}
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: broker2
  labels:
    app: broker
    instance: "2"
spec:
  ports:
    - name: proxy-port
      port: 8002
      protocol: TCP
      targetPort: 8002
    - name: cluster-port
      port: 7002
      protocol: TCP
      targetPort: 7002
  selector:
    app: broker
    instance: "2"
  type: ClusterIP
status:
  loadBalancer: {}
