apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker2
  labels:
    app: broker
    instance: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
      instance: "2"
  strategy: {}
  template:
    metadata:
      labels:
        app: broker
        instance: "2"
    spec:
      containers:
        - image: ciberkleid/s1p-2020-mesh-rs-broker:0.0.1-SNAPSHOT
          name: broker
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s-scaled"
            - name: BROKER_HOST_1
              value: broker1
            - name: BROKER_HOST_2
              value: broker3
          resources: {}
          imagePullPolicy: Always
