apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    app: broker
spec:
  ports:
  - name: broker-port
    port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: broker
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: broker1
  labels:
    app: broker
    instance: "1"
spec:
  ports:
    - name: proxy-port
      port: 8002
      protocol: TCP
      targetPort: 8002
    - name: cluster-port
      port: 7002
      protocol: TCP
      targetPort: 7002
  selector:
    app: broker
    instance: "1"
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: broker2
  labels:
    app: broker
    instance: "2"
spec:
  ports:
    - name: proxy-port
      port: 8002
      protocol: TCP
      targetPort: 8002
    - name: cluster-port
      port: 7002
      protocol: TCP
      targetPort: 7002
  selector:
    app: broker
    instance: "2"
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: broker3
  labels:
    app: broker
    instance: "3"
spec:
  ports:
    - name: proxy-port
      port: 8002
      protocol: TCP
      targetPort: 8002
    - name: cluster-port
      port: 7002
      protocol: TCP
      targetPort: 7002
  selector:
    app: broker
    instance: "3"
  type: ClusterIP
status:
  loadBalancer: {}