io.rsocket.routing.client:
#  route-id: 00000000-0000-0000-0000-000000000003
  service-name: pong
  tags:
    INSTANCE_NAME: pong3
  brokers:
    - host: ${BROKER_HOST:-localhost}
      port: 8002

logging:
  level:
    io.rsocket.routing.client: INFO
---
spring:
  profiles: server
pong:
  client: false

---
spring:
  profiles: pong4

io.rsocket.routing.client:
  route-id: 00000000-0000-0000-0000-000000000004
  service-name: pong
  tags:
    INSTANCE_NAME: pong4

---
spring:
  profiles: broker2

io.rsocket.routing.client:
  brokers:
    - host: ${BROKER_HOST:-localhost}
      port: 8003
---
spring:
  profiles: k8s-scaled

io.rsocket.routing.client:
  service-name: pong
  tags:
    INSTANCE_NAME: ${POD_NAME}
  brokers:
    - host: ${BROKER_HOST:-broker}
      port: 8002
