apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    app: broker
    instance: "1"
spec:
  ports:
    - name: proxy-port
      port: 8002
      protocol: TCP
      targetPort: 8002
    - name: cluster-port
      port: 7002
      protocol: TCP
      targetPort: 7002
  selector:
    app: broker
    instance: "1"
  type: ClusterIP
status:
  loadBalancer: {}
