apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    app: broker
spec:
  ports:
  - name: broker-port
    port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: broker
  type: ClusterIP
status:
  loadBalancer: {}
