io.rsocket.routing.client:
#  route-id: 00000000-0000-0000-0000-000000000001
  service-name: ping
  tags:
    INSTANCE_NAME: ping1
  address:
    pong-rc:
      service_name: pong
  brokers:
    - host: ${BROKER_HOST:-localhost}
      port: 8002

server:
  port: 0
#debug: true
---
spring:
  profiles: ping2

io.rsocket.routing.client:
  route-id: 00000000-0000-0000-0000-000000000002
  tags:
    INSTANCE_NAME: ping2

ping:
  request-type: request_response

---
spring:
  profiles: broker2

io.rsocket.routing.client:
    brokers:
      - host: ${BROKER_HOST:-localhost}
        port: 8003
---
spring:
  profiles: k8s

io.rsocket.routing.client:
  service-name: ping
  tags:
    INSTANCE_NAME: ${POD_NAME}
  brokers:
    - host: ${BROKER_HOST}
      port: 8002
  address:
    pong-rc:
      service_name: pong

ping:
  request-type: request_response
